fix: fix user insert and update tests Failures: ``` tests/test_models/test_threads.py ....                                   [ 44%] tests/test_models/test_users.py .F..F                                    [100%]
=================================== FAILURES ===================================
_________________________________ test_insert __________________________________

users_model = <forum.models.users.Users object at 0x7f6eab730e10>

    def test_insert(users_model):
        """Test insert user from mongodb"""
        external_id = "test_external_id"
        username = "test_username"
        email = "test_email"
>       result = users_model.insert(external_id, username, email)
E       TypeError: Users.insert() takes 1 positional argument but 4 were given

tests/test_models/test_users.py:32: TypeError
_________________________________ test_update __________________________________

users_model = <forum.models.users.Users object at 0x7f6eabad1e90>

    def test_update(users_model):
        """Test update user from mongodb"""
        external_id = "test_external_id"
        username = "test_username"
        email = "test_email"
        users_model.collection.insert_one(
            {
                "_id": external_id,
                "external_id": external_id,
                "username": username,
                "email": email,
            }
        )

        new_username = "new_username"
        new_email = "new_email"
>       result = users_model.update(external_id, new_username, new_email)
E       TypeError: Users.update() takes 1 positional argument but 4 were given

tests/test_models/test_users.py:81: TypeError
=============================== warnings summary ===============================
.tox/py/lib/python3.11/site-packages/mongomock/__version__.py:1
  /home/runner/work/forum/forum/.tox/py/lib/python3.11/site-packages/mongomock/__version__.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.11.9-final-0 -----------
Name                                Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------
forum/__init__.py                       1      0      0      0   100%
forum/apps.py                           4      0      0      0   100%
forum/models/__init__.py                0      0      0      0   100%
forum/models/base_model.py             28      3      8      0    92%   33, 46, 64
forum/models/contents.py               17      1      4      2    86%   37->39, 51->53, 59
forum/models/threads.py                82     17     40     20    70%   72, 76, 174, 175->177, 177->179, 180, 182, 184, 185->187, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208
forum/models/users.py                  33     22     10      0    26%   43-53, 84-106
forum/mongo.py                         22     14      2      0    33%   34-60
forum/settings/__init__.py              0      0      0      0   100%
forum/settings/common.py                5      5      0      0     0%   5-15
forum/settings/production.py            5      5      0      0     0%   5-14
forum/urls.py                           3      3      0      0     0%   5-9
forum/utils.py                         14     14      0      0     0%   3-29
forum/views.py                         19     19      0      0     0%   3-43
tests/__init__.py                       0      0      0      0   100%
tests/test_models/__init__.py           0      0      0      0   100%
tests/test_models/conftest.py          25      0     12      0   100%
tests/test_models/test_threads.py      27      0      2      0   100%
tests/test_models/test_users.py        46     11      2      0    77%   33-38, 82-87
-------------------------------------------------------------------------------
TOTAL                                 331    114     80     22    64%
Coverage XML written to file coverage.xml

=========================== short test summary info ============================
FAILED tests/test_models/test_users.py::test_insert - TypeError: Users.insert...
FAILED tests/test_models/test_users.py::test_update - TypeError: Users.update...
==================== 2 failed, 7 passed, 1 warning in 0.48s ====================
py: exit 1 (1.12 seconds) /home/runner/work/forum/forum> pytest pid=1892
  py: FAIL code 1 (15.79=setup[14.24]+cmd[0.43,1.12] seconds)
  evaluation failed :( (15.87 seconds)
Error: Process completed with exit code 1.
```