FC-0057: implement thread APIs test cases (#73)
* feat: implement thread APIs test cases
- implemented test cases for threads APIs
- add functionality of closing/unclosing thread in thread API.
- remove user_id validation from get threads in case of
  get all threads related to a course.
- update read_states of the user during parent/child comment creation and
  getting thread by thread_id APIs
- fixes users API failure due to missing `type` parameter and
  keep `type` in threads serializer as it is also used in other APIs

* fix: date comparison
- fixed below error that occurred while datetime comparison
```
is_read = read_dates[thread_key] >= thread["last_activity_at"]
TypeError: can't compare offset-naive and offset-aware datetimes
```
- fix and refactor `update_all_users_in_course` method and use `author_id`
  in `build_course_stats` method instead of `author_username`

* fix: add missing param for get request

* feat: update course stats for a user
- update course stats for a user on thread or comment creation and deletion

* test: add test for checking sort order
- added test for checking sorting order of the children of the thread
- fix date comparison error in `build_course_stats` method
  `TypeError: can't compare offset-naive and offset-aware datetimes`

---------

Co-authored-by: Muhammad Faraz  Maqsood <faraz.maqsood@A006-01130.local>
Co-authored-by: Muhammad Faraz  Maqsood <faraz.maqsood@a006-01130.home>